### ISSUE TITLE
Equations not rendering in Menu/TOC/Search Bar

### ISSUE THREAD

**Issue by AhmedThahir** [uni-notes/uni-notes#101]
### Project Contribution

- [X] I have read and agree to the project's [Contribution Guidelines](https://github.com/unnamed-project/.github/CODE_OF_CONDUCT.md)📜

### What happened?

https://github.com/Python-Markdown/markdown/issues/895

**Comment by Fir121** [comment]
Can you send a link as to where this problem is happening in uni-notes?

**Comment by AhmedThahir** [comment]
I forgot where I saw it.

For now, this is an example of the search bar. Notice how the same equations are rendered on the page, but in search. 

https://uni-notes.netlify.app/3_core/computer_architecture/03_isa/?q=arguments

![Screenshot_20231218-230602_Brave](https://github.com/uni-notes/uni-notes/assets/94914628/8c50b0d7-bfd2-415a-ac7f-74080c8a1401)

https://uni-notes.netlify.app/3_core/computer_architecture/03_isa/#example

![Screenshot_20231218-230808_Brave](https://github.com/uni-notes/uni-notes/assets/94914628/ac330fdf-acc3-47ac-88c5-950b9402c7de)

**Comment by Fir121** [comment]
OK so deep dived into this. So basically the math works via the pymdownx.arithmatex extension which parses the markdown and puts any math in a 

`<span class="arithmatex">{{math here}}</span>`
plus escapes some of the special characters inside the math.

Ok so cool right... not yet, next step is the javascript in `docs/javascripts/custom.js` which finds each tag with this label and converts parsed markdown into the equation you see.

I think you know all this, so getting to the problem, my first assumption was since the custom js runs only once at the start, when search results show up it just needs to run again and we would be all set. So I checked this out, but the problem is unfortunately **deeper**.

So the search plugin code is implemented by [mkdocs-material](https://github.com/squidfunk/mkdocs-material/tree/master/material/plugins/search). And I suppose for formatting reasons it has a filter, where it removes any text except those within these specific tags (below)

![image](https://github.com/uni-notes/uni-notes/assets/62911996/ee8b07e2-aae1-469f-8bc2-cbb5da15ef80)

Ok... so sensibly just change the tag from a span to one of these and use some custom css selectors, easy enough since `pymdownx.arithmatex` has a feature `inline_tag` which allows you to change this. BUT the mkdocs material search plugin does one more thing - IT STRIPS AWAY the classes... so there's no way to identify the arithmatex class anymore... 

So in conclusion (or a tl;dr) the solution would be to change up the search plugin a bit. This could be solved by either launching this search plugin separately, or proposing this as a fix to mkdocs (not sure that would work quickly, depends if they even want this as a feature). If you can think of any other solutions or any of my analysis was wrong do let me know!

-------

And yeah, upon editing the search's plugin.py file locally and adding a MutationObserver to md-search__output, we can get the desired output:

![image](https://github.com/uni-notes/uni-notes/assets/62911996/08b85b56-98e5-4c37-b69a-5f63480df636)

I might have a temporary solution (run the math katex parser on all spans and not just the arithmatex class (only inside search), dunno if that works, it will if Katex.js leaves unsupported spans undisturbed without throwing an error, but it may be inefficient and I don't think it is good practice.

**Comment by AhmedThahir** [comment]
**Tweaking the search plugin in depth**
I don't think it's feasible for us to spend time on it.

**Report to mkdocs devs**
We could probably do this

**Run the math katex parser on all spans and not just the arithmatex class (only inside search)**
Seems fine to me
We could also do this for Table of Contents

"It may be inefficient and I don't think it is good practice", but Search and TOC are very small, so I don't think it should be an issue. If this was for all the pages in the site, then yes I would agree it's not the best solution.

**Comment by AhmedThahir** [comment]
Example for rendering failure in Navbar

![image](https://github.com/uni-notes/uni-notes/assets/94914628/98da510f-e9d0-4f85-9beb-9978182182f1)

https://ahmedthahir.github.io/uni-notes/CS_Electives/Machine_Learning/02_Task_T/

**Comment by Fir121** [comment]
Ok I'll look at the toc, and I'll go ahead with the workaround solution for the search bar

**Comment by AhmedThahir** [comment]
Not checking if you have completed, no hurries.

Just checking if any updates.

**Comment by Fir121** [comment]
In a week or so, still have to check what's up with the toc

**Comment by AhmedThahir** [comment]
Any updates?

**Comment by Fir121** [comment]
> **And yeah, upon editing the search's plugin.py file locally and adding a MutationObserver to md-search__output, we can get the desired output:**
> If this is easy and already implemented, let's go ahead with this

This wont be possible as it edits files in site-packages. Ie the underlying pip module needs to be edited



> **Run the math katex parser on all spans and not just the arithmatex class (only inside search)**
> Seems fine to me
> We could also do this for Table of Contents

This is not working out either. Not sure if it is because of an edge case or just over processing on the page.

**Comment by AhmedThahir** [comment]
Alright! No issues, we can get back to this later.
