### ISSUE TITLE
Netlify Deployment Sensitivity Settings

### ISSUE THREAD

**Issue by AhmedThahir** [uni-notes/uni-notes#123]
Currently deploy previews require approval from me due to the addition of the environment variable.

![image](https://github.com/uni-notes/uni-notes/assets/94914628/aa488236-a74c-4d76-a218-8dd77451a8e5)

Is it safe to change the settings?

**Comment by Fir121** [comment]
Ooh I think this is to avoid someone putting malicious code like
```
print(env.var)
```
In their PR. Is there any setting to allow deploy only for trusted individuals? Otherwise you can deploy without the variables in that case the preview won't contain the git committers information.

By the way is this new? Because I saw one log after we made the changes which worked without issues?

**Comment by AhmedThahir** [comment]
> By the way is this new? Because I saw one log after we made the changes which worked without issues?

I had approved that manually

**Comment by AhmedThahir** [comment]
> Is there any setting to allow deploy only for trusted individuals?
To specify trusted individuals, it seems like we need Netlify Premium

> Otherwise you can deploy without the variables in that case the preview won't contain the git committers information.
Yepp, I've done it
